version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map container's port 8000 to host's port 8000
    depends_on:
      - db  # The web service depends on the database starting first
    environment:
      DATABASE_HOST: "db"  # Reference the database container name (not localhost)
      DATABASE_PORT: ${DATABASE_PORT}  # Load port from .env file
      DATABASE_USER: ${DATABASE_USER}  # Load username from .env file
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}  # Load password from .env file
      DATABASE_NAME: ${DATABASE_NAME}  # Load database name from .env file
      DATABASE_URL: >-
        postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}

  db:
    image: postgres:15  # PostgreSQL official Docker image
    environment:
      POSTGRES_USER: ${DATABASE_USER}  # Set PostgreSQL user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  # Set PostgreSQL password
      POSTGRES_DB: ${DATABASE_NAME}  # Set PostgreSQL database name
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"  # Map database port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

volumes:
  postgres_data:  # Define a persistent volume for PostgreSQL